In [2]:
import numpy as np
data1 = [6, 7.5, 8, 0, 1]

arr1 = np.array(data1)

In [3]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [4]:
arr2 = np.array(data2)
arr2.ndim

2

In [5]:
arr2.shape

(2, 4)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [8]:
np.zeros((3,2))

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [11]:
np.arange(10, 20, 3)

array([10, 13, 16, 19])

In [12]:
np.identity(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [13]:
arr1 = np.array([1,2,3], dtype=np.float64)

In [14]:
int_arr1 = arr1.astype(np.int64)

In [15]:
int_arr1

array([1, 2, 3])

In [16]:
arr = np.arange(10)

In [17]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [18]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [20]:
x = np.random.randn(8)

In [21]:
x

array([-1.3606586 , -0.58288193, -0.82091391,  1.08733806, -0.74305008,
       -0.63487695, -0.85361652,  0.0603103 ])

In [23]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [24]:
resut = np.where(cond, xarr, yarr)

In [25]:
arr = np.random.randn(4,4)

In [26]:
arr

array([[-0.23720114,  1.43599506,  0.13321585, -0.66442704],
       [-0.63835441,  1.26899227,  0.54429871, -1.22380303],
       [ 1.66048928,  1.62338152, -1.67481265,  1.25775664],
       [ 0.26020864,  1.9021542 ,  0.32014198,  0.03811906]])

In [29]:
np.where(arr > 1, 2, -2)


array([[-2,  2, -2, -2],
       [-2,  2, -2, -2],
       [ 2,  2, -2,  2],
       [-2,  2, -2, -2]])

In [30]:
arr = np.random.randn(100)
(arr > 0).sum()

43

In [31]:
bools = np.array([False, False, True, False])

bools.any()

True

In [32]:
bools.all()

False

In [33]:
arr.sort()

In [34]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
np.unique(names)

array(['Bob', 'Joe', 'Will'],
      dtype='<U4')